import "./globals.css";
import { Roboto } from "next/font/google";
import Sidebar from "@/components/sidebar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Guru Kripa Institution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex h-screen w-screen">
          <nav className="bg-[#1e1e1e] w-2/12 z-10 sticky top-0 left-0">
            <Sidebar />
          </nav>
          <main className="w-10/12 bg-[#eee]">{children}</main>
        </div>
      </body>
    </html>
  );
}
